### PR TITLE
fix(ContextGraphBuilder): don't throw if DbContext contains non json:api resource

### LINKED ISSUE #249: Problem with AppDbContext derived from IdentityDbContext
Hello,
after update from 2.1.11 to 2.2, there si error in Startup.cs inicialization:
`services.AddJsonApi<AppDbContext>`
> Type does not implement 'IIdentifiable<TId>'\r\nParameter name: resourceType

Stack trace:
> at JsonApiDotNetCore.Builders.ContextGraphBuilder.GetIdType(Type resourceType)
   at JsonApiDotNetCore.Builders.ContextGraphBuilder.AddDbContext[T]()
   at JsonApiDotNetCore.Extensions.IServiceCollectionExtensions.<>c__2`1.<AddJsonApi>b__2_0(IContextGraphBuilder builder)
   at JsonApiDotNetCore.Configuration.JsonApiOptions.BuildContextGraph(Action`1 builder)
   at JsonApiDotNetCore.Extensions.IServiceCollectionExtensions.AddJsonApi[TContext](IServiceCollection services, Action`1 options, IMvcBuilder mvcBuilder)

If AppDbContext derived from DbContext, everything is ok, but my AppDbContext derived from IdentityDbContext<User,Role,int>.

Can you make some investigation? Thank you.

### PR DESCRIPTION
**Pull request by jaredcnance**
Closes #249 
Also begins work for #170 

#### BUG FIX
- [x] reproduce issue in tests
- [x] fix issue
- [x] bump package version

### CODE REVIEW

**Comment by wayne-o** [comment]
I just bumped into this one but I am using latest AFAIK

Is this on Nuget yet?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
