### ISSUE TITLE
Problem with AppDbContext derived from IdentityDbContext

### ISSUE THREAD

**Issue by milosloub** [json-api-dotnet/JsonApiDotNetCore#249]
Hello,
after update from 2.1.11 to 2.2, there si error in Startup.cs inicialization:
`services.AddJsonApi<AppDbContext>`
> Type does not implement 'IIdentifiable<TId>'\r\nParameter name: resourceType

Stack trace:
> at JsonApiDotNetCore.Builders.ContextGraphBuilder.GetIdType(Type resourceType)
   at JsonApiDotNetCore.Builders.ContextGraphBuilder.AddDbContext[T]()
   at JsonApiDotNetCore.Extensions.IServiceCollectionExtensions.<>c__2`1.<AddJsonApi>b__2_0(IContextGraphBuilder builder)
   at JsonApiDotNetCore.Configuration.JsonApiOptions.BuildContextGraph(Action`1 builder)
   at JsonApiDotNetCore.Extensions.IServiceCollectionExtensions.AddJsonApi[TContext](IServiceCollection services, Action`1 options, IMvcBuilder mvcBuilder)

If AppDbContext derived from DbContext, everything is ok, but my AppDbContext derived from IdentityDbContext<User,Role,int>.

Can you make some investigation? Thank you.

**Comment by jaredcnance** [comment]
So, this is the problem area:

https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/e30f911f9bdb1185d1b0bd0a1ccfa7694fcb8c18/src/JsonApiDotNetCore/Builders/ContextGraphBuilder.cs#L136-L146

I'm not sure right now why this was ever working. The correct behavior would be to log a warning. The reason it fails with the `IdentityDbContext` is because the Identity models do not implement `IIdentifiable` which should be handled. And we shouldn't require all models on a context to be JsonAPI resources. Depending on the size of your context you could temporarily manually construct the context graph:

```csharp
services.AddJsonApi(options => {
        options.BuildContextGraph((builder) => {
            builder.AddResource<MyModel>("my-models");
        });
    }, mvcBuilder);
```

https://json-api-dotnet.github.io/#/context-graph

I will work on having a fix in v2.2.1 as soon as possible.

**Comment by milosloub** [comment]
For me this temporary solution is ok until it is fixed.
Btw thank you for this library. It's total masterpiece

**Comment by jaredcnance** [comment]
@milosloub please upgrade to 2.2.1 and let me know if that solves your problem.

**Comment by milosloub** [comment]
@jaredcnance Wow, that was fast. After upgrade it works perfectly. Thank you
